VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Lambda"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "Lambda.Primitives"
Option Explicit

Public Function Add(ParamArray Items() As Variant) As Lambda
Attribute Add.VB_UserMemId = 0
End Function
Public Function Run() As Variant: End Function
