VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "INullary"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Description = "Function Expression"
'@Folder("Functional.Abstractions")
Option Explicit

Public Function Run() As Variant
	Attribute Run.VB_Description = "Executes the calculation"
  Attribute Run.VB_UserMemID = 0
End Function
